apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corx.fullname" . }}-config
  labels:
    {{- include "corx.labels" . | nindent 4 }}
data:
  config.toml: |
{{ .Values.config | indent 4 }}
